[profile.default]
src = "src"
test = "test"
script = "scripts"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
#    "@uniswap/=lib/v3-core/contracts/",

solc = "0.8.34"
auto_detect_remappings = true
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
eth_rpc_url = "https://ethereum.reth.rs/rpc"
#eth_rpc_url = "https://mainnet.infura.io"

#gas_reports = ["Counter", "Token"]
#gas_reports_ignore = ["Test", "Script"]

#https://www.getfoundry.sh/config/reference/formatter
[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
ignore = ["src/legacy/**"]

[lint]
severity = ["high", "med", "low"]
#severity = ["high", "med"]  # Only high and medium severity; severity levels = high, med, low, info, gas, code-size
exclude_lints = ["mixed-case-function", "asm-keccak256"]
#"custom-errors"
ignore = ["src/legacy/**", "test/**"]
#Lint suppression: https://www.getfoundry.sh/forge/linting#inline-suppression

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x1234"

[profile.ci]

[rpc_endpoints]
sei_testnet = "https://evm-rpc-testnet.sei-apis.com"
sei_mainnet = "https://evm-rpc.sei-apis.com"

[profile.production]
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
